export const cuisineList = [
  "Aromatic Aloo Affair",
  "Arbi Chronicles",
  "Baingan & Beyond",
  "Bharwa-e-Biryani",
  "Chana & Chole",
  "Chicken",
  "Delightful Dals & Dishes",
  "Drinks",
  "Desi",
  "East Meets West",
  "Flavors of India ",
  "Fast Special",
  "Gajjar & Gravy",
  "Healthy",
  "Indian",
  "Jalapeño",
  "Khaas Kuisine",
  "Lahori Delights",
  "Murthal Special",
  "Mughlai",
  "Non Veg",
  "North Indian",
  "Noodles",
  "Organic",
  "Rice",
  "Pasta",
  "Pizza",
  "Salads",
  "Seafood",
  "Sweets",
  "South Indian",
  "Spice Saga",
  "Tandoori",
  "Tiffin",
  "Thali",
  "Vegeratian",
];
